### ISSUE TITLE
doesnt work

### ISSUE THREAD

**Issue by vutran1710** [codeship-library/kubectl#3]
Kubectl never receives the context from the encrypted env file in my case. I tried a lot without success. 
Please have a look

My build log
```
kubectl   build/pull started
kubectl   build/pull finished successfully
kubectl   apiVersion: v1
kubectl  clusters: []
kubectl  contexts: []
kubectl  users: []
....
```

my config is exactly as in the document's example
```yaml
kubectl:
  build:
    image: codeship/kubectl
    dockerfile: Dockerfile
  encrypted_env_file:
    - k8s-env.encrypted
```

and the steps
```yaml
- type: serial
  steps:
    - name: check response to kubectl config
      tag: master
      service: kubectl
      command: kubectl config view
```

the `codeship.aes` matches perfectly with my current AES key
Nothing seems wrong so far.
